### PR TITLE
install test with travis-ci + Vagrantfile to make development more lean

### PR DESCRIPTION
**Pull request by CesarBallardini**
The Vagrant + Virtualbox environment allows to test on  a VM with operating system different from the workstation programmer.

The Travis-CI file `.travis.yml` triggers a fresh test install on every push to `master`.

### CODE REVIEW

**Comment by gillesdubois** [comment]
Hi @CesarBallardini 

Thanks a lot for your contribution.
I'll add this repository in our travis testing.

In the readme.md you still use the your travis link for status.
Could you update it and use : https://travis-ci.org/github/ocsinventory-ng ?

Thanks again.

Regards,
Gilles.

**Comment by CesarBallardini** [comment]
Added 7c64902 commit to master on  CesarBallardini/Ansible-Role-For-UnixAgent, this fixed the travis URL link

Please, check to see if it is available on this PR.

Cheers,
César.

**Comment by gillesdubois** [comment]
Hi,

It seems OK on my side, I'm gonna add the ansible role repository on Travis and merge this PR right after.

Thanks a lot for your contribution.

Gilles.

**Comment by CesarBallardini** [comment]
@gillesdubois thank you for your time!

**Pull request merged**
