### PR TITLE
Syntax modernization, dropped Ubuntu 14.04, CentOS 6 and Debian 7 support, add CentOS 8, Debian 10 and Ubuntu 20.04 support

### PR DESCRIPTION
**Pull request by fourstepper**
This PR provides compatibility with new versions of Linux distributions while dropping support for older releases of those distributions. It also aims to improve the quality of syntax of the Ansible code.

Aside from this quick fix of a PR, it would probably be a good idea to use either the available or distribution-provided packages for the installation instead of compiling from source. I suggest that if we want to go through with that effort, a new repository with code-from-scratch is written for that use-case, ideally with some testing of the role itself.

### CODE REVIEW

**Comment by fourstepper** [comment]
Distributions tested with `molecule` against images provides by @geerlingguy (https://ansible.jeffgeerling.com):
Debian 8
Debian 9
Debian 10

CentOS 7
CentOS 8

Ubuntu 16.04
Ubuntu 18.04
Ubuntu 20.04

**Comment by fourstepper** [comment]
@gillesdubois could you please check this? The syntax clean-up is not perfect, but I would like to see this merged for compatibility reasons

**Comment by gillesdubois** [comment]
Hi @fourstepper 

No problems I was just waiting for the Unit Test to work properly :)

Regards,
Gilles.

**Comment by fourstepper** [comment]
@gillesdubois thanks - what do you think of refactoring the role to make use of the official packages?

**Comment by gillesdubois** [comment]
@fourstepper it would be really nice I think. Since we have official repository it should be the default behavior but still provide the option to install from source

**Comment by fourstepper** [comment]
@gillesdubois do you think it would be better to create a separate repo for this?

**Comment by gillesdubois** [comment]
Would it be possible to add the new role in the same repository ? I don't think creating new repository is the best way to proceed. It'll only confuse most of our user base imo.

Gilles.

**Pull request merged**
